apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "blacksentinel-pulse.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.env.secretKey | b64enc | quote }}
  database-url: {{ .Values.env.databaseUrl | b64enc | quote }}
  redis-url: {{ .Values.env.redisUrl | b64enc | quote }}
  neo4j-password: {{ .Values.env.neo4jPassword | b64enc | quote }}
