import enum
from datetime import datetime

from sqlalchemy import (
    Column, Integer, String, Boolean, DateTime, Enum, ForeignKey, Text, JSON, Float
)
from sqlalchemy.orm import relationship

from app.core.database import Base


class AlertSeverity(str, enum.Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class AlertStatus(str, enum.Enum):
    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"
    AUTO_RESOLVED = "auto_resolved"


class Alert(Base):
    """Intelligent alert generated by Pulse analysis."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_id = Column(String(36), unique=True, nullable=False, index=True)
    title = Column(String(500), nullable=False)
    description = Column(Text)
    severity = Column(Enum(AlertSeverity), nullable=False, index=True)
    status = Column(Enum(AlertStatus), default=AlertStatus.OPEN)

    # Source
    alert_type = Column(String(100), nullable=False)  # vulnerability, exposure, anomaly, threat, compliance
    source = Column(String(100))
    rule_id = Column(String(100))
    detection_method = Column(String(100))

    # Correlation
    correlation_id = Column(String(36))
    related_alerts = Column(JSON, default=list)
    incident_id = Column(String(36), index=True)

    # AI Analysis
    ai_confidence = Column(Float)
    ai_explanation = Column(Text)
    ai_recommendation = Column(Text)
    auto_remediation_available = Column(Boolean, default=False)

    # Context
    asset_id = Column(Integer, ForeignKey("assets.id"), index=True)
    vulnerability_id = Column(Integer, ForeignKey("vulnerabilities.id"))
    threat_intel_id = Column(Integer, ForeignKey("threat_intelligence.id"))

    # Impact
    business_impact = Column(String(50))
    blast_radius = Column(Integer)  # Number of affected assets
    exploitability = Column(Float)

    # Evidence
    evidence = Column(JSON, default=list)
    raw_data = Column(JSON, default=dict)

    # Notification
    notified = Column(Boolean, default=False)
    notification_channels = Column(JSON, default=list)
    acknowledged_by = Column(Integer, ForeignKey("users.id"))
    acknowledged_at = Column(DateTime)

    # Resolution
    resolution_notes = Column(Text)
    resolved_by = Column(Integer, ForeignKey("users.id"))
    resolved_at = Column(DateTime)
    auto_resolved = Column(Boolean, default=False)

    # SLA
    sla_deadline = Column(DateTime)
    sla_breached = Column(Boolean, default=False)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    organization_id = Column(Integer, ForeignKey("organizations.id"), nullable=False)
    organization = relationship("Organization", back_populates="alerts")
    assigned_to = relationship("User", foreign_keys=[acknowledged_by], backref="assigned_alerts")

    def __repr__(self):
        return f"<Alert {self.alert_id} ({self.severity})>"

    @property
    def is_escalated(self) -> bool:
        return self.severity in (AlertSeverity.CRITICAL, AlertSeverity.HIGH) and self.status == AlertStatus.OPEN
